"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnitSupportProduction = exports.UnitSupportFood = exports.Unhappiness = exports.Trade = exports.Research = exports.PopulationSupportFood = exports.Luxuries = exports.Happiness = exports.Gold = exports.FoodStorage = exports.Production = exports.Food = void 0;
var Yields_1 = require("@civ-clone/civ1-world/Yields");
Object.defineProperty(exports, "Food", { enumerable: true, get: function () { return Yields_1.Food; } });
Object.defineProperty(exports, "Production", { enumerable: true, get: function () { return Yields_1.Production; } });
var FoodStorage_1 = require("@civ-clone/core-city-growth/Yields/FoodStorage");
Object.defineProperty(exports, "FoodStorage", { enumerable: true, get: function () { return FoodStorage_1.FoodStorage; } });
var Gold_1 = require("@civ-clone/base-city-yield-gold/Gold");
Object.defineProperty(exports, "Gold", { enumerable: true, get: function () { return Gold_1.Gold; } });
var Happiness_1 = require("@civ-clone/base-city-yield-happiness/Happiness");
Object.defineProperty(exports, "Happiness", { enumerable: true, get: function () { return Happiness_1.Happiness; } });
var Luxuries_1 = require("@civ-clone/base-city-yield-luxuries/Luxuries");
Object.defineProperty(exports, "Luxuries", { enumerable: true, get: function () { return Luxuries_1.Luxuries; } });
var PopulationSupportFood_1 = require("@civ-clone/base-city-yield-population-support-food/PopulationSupportFood");
Object.defineProperty(exports, "PopulationSupportFood", { enumerable: true, get: function () { return PopulationSupportFood_1.PopulationSupportFood; } });
var Research_1 = require("@civ-clone/base-city-yield-research/Research");
Object.defineProperty(exports, "Research", { enumerable: true, get: function () { return Research_1.Research; } });
var Trade_1 = require("@civ-clone/base-terrain-yield-trade/Trade");
Object.defineProperty(exports, "Trade", { enumerable: true, get: function () { return Trade_1.Trade; } });
var Unhappiness_1 = require("@civ-clone/base-city-yield-unhappiness/Unhappiness");
Object.defineProperty(exports, "Unhappiness", { enumerable: true, get: function () { return Unhappiness_1.Unhappiness; } });
var UnitSupportFood_1 = require("@civ-clone/base-city-yield-unit-support-food/UnitSupportFood");
Object.defineProperty(exports, "UnitSupportFood", { enumerable: true, get: function () { return UnitSupportFood_1.UnitSupportFood; } });
var UnitSupportProduction_1 = require("@civ-clone/base-city-yield-unit-support-production/UnitSupportProduction");
Object.defineProperty(exports, "UnitSupportProduction", { enumerable: true, get: function () { return UnitSupportProduction_1.UnitSupportProduction; } });
//# sourceMappingURL=Yields.js.map